### ISSUE TITLE
Not working in Windows..

### ISSUE THREAD

**Issue by Gruntfuggly** [kisstkondoros/gutter-preview#19]
Version 0.14.0

From the console:
```
 ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at context.subscriptions.push.vscode.window.onDidChangeActiveTextEditor.e (C:\Users\nscott\.vscode\extensions\kisstkondoros.vscode-gutter-preview-0.14.0\out\src\decorator.js:113:25)
```

Don't think that it's the cause of the problem, but I'm not seeing anything in the gutter or popups?

Works fine under Ubuntu though...!?

**Comment by kisstkondoros** [comment]
Fixed in version 0.14.1, sorry for the inconvenience.

**Comment by Gruntfuggly** [comment]
The errors are gone but I'm still not seeing anything in the gutter or popups.
I traced through the code and it looks like the call to the language server in `symbolUpdater` always returns an object with an empty array: 
```{"images":[]}```
On my Ubuntu machine, the same file returns:
```
{"images":[{"originalImagePath":"http://cdn.discordapp.com/attachments/431034722131378179/487700709760958469/image0.jpg","imagePath":"/tmp/tmp-11377yjVTTqsB4uob.jpg","range":{"start":{"line":1,"character":36},"end":{"line":1,"character":117}}},{"originalImagePath":"http://cdn.discordapp.com/attachments/431034722131378179/488250545560354826/image0.jpg","imagePath":"/tmp/tmp-11377y1uk8vNTkTDL.jpg","range":{"start":{"line":7,"character":44},"end":{"line":7,"character":125}}},{"originalImagePath":"http://cdn.discordapp.com/attachments/431034722131378179/489138296031805452/image0.jpg","imagePath":"/tmp/tmp-11377bApD1VnVf9Zr.jpg","range":{"start":{"line":15,"character":36},"end":{"line":15,"character":117}}},{"originalImagePath":"http://cdn.discordapp.com/attachments/431034722131378179/489428099986096129/image0.png","imagePath":"/tmp/tmp-11377EdnF7lPj3j9F.png","range":{"start":{"line":26,"character":44},"end":{"line":26,"character":125}}}]}
```

Any idea what is going on?

**Comment by kisstkondoros** [comment]
Strange, I'll have a look at it

**Comment by kisstkondoros** [comment]
I have no access to a windows machine at the moment (I'm downloading a VM to test this) could you provide some more details in the meantime perhaps?

**Comment by kisstkondoros** [comment]
VM is running... :+1:

**Comment by kisstkondoros** [comment]
:crossed_fingers: 0.14.2 is published

**Comment by Gruntfuggly** [comment]
Works a treat! Thank You!
